/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.DemographicInfo;
import javax.swing.JOptionPane;

/**
 *
 * @author Urvi
 */
public class CreateDemographicInfo extends javax.swing.JPanel {
    DemographicInfo demographicInfo;

    /**
     * Creates new form CreateDemographicInfo
     */
    public CreateDemographicInfo(DemographicInfo demographicInfo) {
        initComponents();
        this.demographicInfo = demographicInfo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblDemoInfo = new javax.swing.JLabel();
        lblfname = new javax.swing.JLabel();
        lbllname = new javax.swing.JLabel();
        lblphonenumber = new javax.swing.JLabel();
        lbldob = new javax.swing.JLabel();
        lblage = new javax.swing.JLabel();
        lblheight = new javax.swing.JLabel();
        lblweight = new javax.swing.JLabel();
        lblssn = new javax.swing.JLabel();
        txtfname = new javax.swing.JTextField();
        txtlname = new javax.swing.JTextField();
        txtphonenumber = new javax.swing.JTextField();
        txtdob = new javax.swing.JTextField();
        txtage = new javax.swing.JTextField();
        txtheight = new javax.swing.JTextField();
        txtweight = new javax.swing.JTextField();
        txtssn = new javax.swing.JTextField();
        btndemosave = new javax.swing.JButton();

        setBackground(new java.awt.Color(212, 196, 196));
        setLayout(new java.awt.GridBagLayout());

        lblDemoInfo.setFont(new java.awt.Font("Footlight MT Light", 1, 26)); // NOI18N
        lblDemoInfo.setForeground(new java.awt.Color(102, 0, 51));
        lblDemoInfo.setText("Demographic Information");
        lblDemoInfo.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(37, 69, 0, 0);
        add(lblDemoInfo, gridBagConstraints);

        lblfname.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        lblfname.setText("First Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 125, 0, 0);
        add(lblfname, gridBagConstraints);

        lbllname.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        lbllname.setText("Last Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 127, 0, 0);
        add(lbllname, gridBagConstraints);

        lblphonenumber.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        lblphonenumber.setText("Phone Number:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 96, 0, 0);
        add(lblphonenumber, gridBagConstraints);

        lbldob.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        lbldob.setText("Date Of Birth(mm/dd/yyyy):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 8, 0, 0);
        add(lbldob, gridBagConstraints);

        lblage.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        lblage.setText("Age:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 171, 0, 0);
        add(lblage, gridBagConstraints);

        lblheight.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        lblheight.setText("Height(cms):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 114, 0, 0);
        add(lblheight, gridBagConstraints);

        lblweight.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        lblweight.setText("Weight(pounds):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 87, 0, 0);
        add(lblweight, gridBagConstraints);

        lblssn.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        lblssn.setText("Social Security Number:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 37, 0, 0);
        add(lblssn, gridBagConstraints);

        txtfname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 143;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 23, 0, 21);
        add(txtfname, gridBagConstraints);

        txtlname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 143;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 23, 0, 21);
        add(txtlname, gridBagConstraints);

        txtphonenumber.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 143;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 23, 0, 21);
        add(txtphonenumber, gridBagConstraints);

        txtdob.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 143;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 23, 0, 21);
        add(txtdob, gridBagConstraints);

        txtage.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 143;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 23, 0, 21);
        add(txtage, gridBagConstraints);

        txtheight.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 143;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 23, 0, 21);
        add(txtheight, gridBagConstraints);

        txtweight.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 143;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 23, 0, 21);
        add(txtweight, gridBagConstraints);

        txtssn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 143;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 23, 0, 21);
        add(txtssn, gridBagConstraints);

        btndemosave.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        btndemosave.setForeground(new java.awt.Color(102, 0, 51));
        btndemosave.setText("Save");
        btndemosave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndemosaveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 195, 11, 0);
        add(btndemosave, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btndemosaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndemosaveActionPerformed
       demographicInfo.setFirstName(txtfname.getText());
       demographicInfo.setLastName(txtlname.getText());
       demographicInfo.setPhoneNo(txtphonenumber.getText());
       demographicInfo.setDateOfBirth(txtdob.getText());
       demographicInfo.setAge(txtage.getText());
       demographicInfo.setHeight(txtheight.getText());
       demographicInfo.setWeight(txtweight.getText());
       demographicInfo.setSSN(txtssn.getText());
       
        JOptionPane.showMessageDialog(this, "Information saved!");
    }//GEN-LAST:event_btndemosaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndemosave;
    private javax.swing.JLabel lblDemoInfo;
    private javax.swing.JLabel lblage;
    private javax.swing.JLabel lbldob;
    private javax.swing.JLabel lblfname;
    private javax.swing.JLabel lblheight;
    private javax.swing.JLabel lbllname;
    private javax.swing.JLabel lblphonenumber;
    private javax.swing.JLabel lblssn;
    private javax.swing.JLabel lblweight;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtdob;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtheight;
    private javax.swing.JTextField txtlname;
    private javax.swing.JTextField txtphonenumber;
    private javax.swing.JTextField txtssn;
    private javax.swing.JTextField txtweight;
    // End of variables declaration//GEN-END:variables
}
