/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.AddressInfo;
import javax.swing.JOptionPane;

/**
 *
 * @author Urvi
 */
public class CreateAddressInfo extends javax.swing.JPanel {
    AddressInfo addressInfo;

    /**
     * Creates new form CreateAddressInfo
     */
    public CreateAddressInfo(AddressInfo addressInfo) {
        initComponents();
        this.addressInfo = addressInfo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lbladdressinfo = new javax.swing.JLabel();
        lblstreetadd = new javax.swing.JLabel();
        lblcity = new javax.swing.JLabel();
        lblstate = new javax.swing.JLabel();
        lblzipcode = new javax.swing.JLabel();
        txtstreetadd = new javax.swing.JTextField();
        txtcity = new javax.swing.JTextField();
        txtstate = new javax.swing.JTextField();
        txtzipcode = new javax.swing.JTextField();
        btnaddsave = new javax.swing.JButton();

        setBackground(new java.awt.Color(212, 196, 196));
        setLayout(new java.awt.GridBagLayout());

        lbladdressinfo.setFont(new java.awt.Font("Footlight MT Light", 1, 26)); // NOI18N
        lbladdressinfo.setForeground(new java.awt.Color(102, 0, 51));
        lbladdressinfo.setText("Address Information");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(36, 77, 0, 0);
        add(lbladdressinfo, gridBagConstraints);

        lblstreetadd.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        lblstreetadd.setText("Street Address:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 20, 0, 0);
        add(lblstreetadd, gridBagConstraints);

        lblcity.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        lblcity.setText("City:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(36, 93, 0, 0);
        add(lblcity, gridBagConstraints);

        lblstate.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        lblstate.setText("State:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(31, 86, 0, 0);
        add(lblstate, gridBagConstraints);

        lblzipcode.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        lblzipcode.setText("ZipCode:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 72, 0, 0);
        add(lblzipcode, gridBagConstraints);

        txtstreetadd.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 144;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(37, 87, 0, 37);
        add(txtstreetadd, gridBagConstraints);

        txtcity.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 144;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(34, 87, 0, 37);
        add(txtcity, gridBagConstraints);

        txtstate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 144;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 87, 0, 37);
        add(txtstate, gridBagConstraints);

        txtzipcode.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtzipcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtzipcodeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 144;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 87, 0, 37);
        add(txtzipcode, gridBagConstraints);

        btnaddsave.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        btnaddsave.setForeground(new java.awt.Color(102, 0, 51));
        btnaddsave.setText("Save");
        btnaddsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddsaveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(34, 31, 28, 0);
        add(btnaddsave, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void txtzipcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtzipcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtzipcodeActionPerformed

    private void btnaddsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddsaveActionPerformed
        addressInfo.setStreetAddress(txtstreetadd.getText());
        addressInfo.setCity(txtcity.getText());
        addressInfo.setState(txtstate.getText());
        addressInfo.setZipCode(txtzipcode.getText());
       
        JOptionPane.showMessageDialog(this, "Information saved!");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnaddsaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddsave;
    private javax.swing.JLabel lbladdressinfo;
    private javax.swing.JLabel lblcity;
    private javax.swing.JLabel lblstate;
    private javax.swing.JLabel lblstreetadd;
    private javax.swing.JLabel lblzipcode;
    private javax.swing.JTextField txtcity;
    private javax.swing.JTextField txtstate;
    private javax.swing.JTextField txtstreetadd;
    private javax.swing.JTextField txtzipcode;
    // End of variables declaration//GEN-END:variables
}
