/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.BankingInfo;
import Business.CheckingAccount;
import Business.SavingsAccount;
import java.awt.event.KeyEvent;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author Urvi
 */
public class CreateBankingInfo extends javax.swing.JPanel {
    BankingInfo bankingInfo;
    SavingsAccount savingsAccount;
    CheckingAccount checkingAccount;

    /**
     * Creates new form CreateBankingInfo
     */
    public CreateBankingInfo(BankingInfo bankingInfo, SavingsAccount savingsAccount,CheckingAccount checkingAccount) {
        initComponents();
        this.bankingInfo = bankingInfo;
        this.savingsAccount = savingsAccount;
        this.checkingAccount = checkingAccount;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblbankinginfo = new javax.swing.JLabel();
        lblbankname = new javax.swing.JLabel();
        lblbankroutingno = new javax.swing.JLabel();
        lblaccnosave = new javax.swing.JLabel();
        lblaccnochk = new javax.swing.JLabel();
        lblaccbalsave = new javax.swing.JLabel();
        lblaccbalchk = new javax.swing.JLabel();
        lblacctypesave = new javax.swing.JLabel();
        lblacctypechk = new javax.swing.JLabel();
        txtbankname = new javax.swing.JTextField();
        txtroutingno = new javax.swing.JTextField();
        txtaccnosave = new javax.swing.JTextField();
        txtaccnochk = new javax.swing.JTextField();
        txtaccbalsave = new javax.swing.JTextField();
        txtaccbalchk = new javax.swing.JTextField();
        btnbanksave = new javax.swing.JButton();

        setBackground(new java.awt.Color(212, 196, 196));
        setLayout(new java.awt.GridBagLayout());

        lblbankinginfo.setFont(new java.awt.Font("Footlight MT Light", 1, 26)); // NOI18N
        lblbankinginfo.setForeground(new java.awt.Color(102, 0, 51));
        lblbankinginfo.setText("Banking Information");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(31, 74, 0, 0);
        add(lblbankinginfo, gridBagConstraints);

        lblbankname.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        lblbankname.setText("Bank Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(45, 9, 0, 0);
        add(lblbankname, gridBagConstraints);

        lblbankroutingno.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        lblbankroutingno.setText("Bank Routing Number:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 0, 0);
        add(lblbankroutingno, gridBagConstraints);

        lblaccnosave.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        lblaccnosave.setText("Account Number:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 22, 0, 0);
        add(lblaccnosave, gridBagConstraints);

        lblaccnochk.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        lblaccnochk.setText("Account Number:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 15;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 43, 0, 0);
        add(lblaccnochk, gridBagConstraints);

        lblaccbalsave.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        lblaccbalsave.setText("Account Balance:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 22, 0, 0);
        add(lblaccbalsave, gridBagConstraints);

        lblaccbalchk.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        lblaccbalchk.setText("Account Balance:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 15;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 43, 0, 0);
        add(lblaccbalchk, gridBagConstraints);

        lblacctypesave.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        lblacctypesave.setText("Savings Account");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(71, 104, 0, 0);
        add(lblacctypesave, gridBagConstraints);

        lblacctypechk.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        lblacctypechk.setText("Checking Account");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 39;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(71, 1, 0, 0);
        add(lblacctypechk, gridBagConstraints);

        txtbankname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtbankname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbanknameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 15;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 49;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 133;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(42, 46, 0, 0);
        add(txtbankname, gridBagConstraints);

        txtroutingno.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 15;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 49;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 133;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 46, 0, 0);
        add(txtroutingno, gridBagConstraints);

        txtaccnosave.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 133;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 38, 0, 0);
        add(txtaccnosave, gridBagConstraints);

        txtaccnochk.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 88;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 51;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 133;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 15, 0, 0);
        add(txtaccnochk, gridBagConstraints);

        txtaccbalsave.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 134;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 38, 0, 0);
        add(txtaccbalsave, gridBagConstraints);

        txtaccbalchk.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 88;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 52;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 134;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 15, 0, 19);
        add(txtaccbalchk, gridBagConstraints);

        btnbanksave.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        btnbanksave.setForeground(new java.awt.Color(102, 0, 51));
        btnbanksave.setText("Save");
        btnbanksave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbanksaveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(42, 6, 34, 0);
        add(btnbanksave, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void txtbanknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbanknameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbanknameActionPerformed

    private void btnbanksaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbanksaveActionPerformed
        bankingInfo.setBankName(txtbankname.getText());
        bankingInfo.setBankRoutingNumber(txtroutingno.getText());
        savingsAccount.setSavebankAccNumber(txtaccnosave.getText());
        savingsAccount.setSaveaccBalance(txtaccbalsave.getText());
        checkingAccount.setChkbankAccNumber(txtaccnochk.getText());
        checkingAccount.setChkaccBalance(txtaccbalchk.getText());
        
        JOptionPane.showMessageDialog(this, "Information saved!");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbanksaveActionPerformed
        
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbanksave;
    private javax.swing.JLabel lblaccbalchk;
    private javax.swing.JLabel lblaccbalsave;
    private javax.swing.JLabel lblaccnochk;
    private javax.swing.JLabel lblaccnosave;
    private javax.swing.JLabel lblacctypechk;
    private javax.swing.JLabel lblacctypesave;
    private javax.swing.JLabel lblbankinginfo;
    private javax.swing.JLabel lblbankname;
    private javax.swing.JLabel lblbankroutingno;
    private javax.swing.JTextField txtaccbalchk;
    private javax.swing.JTextField txtaccbalsave;
    private javax.swing.JTextField txtaccnochk;
    private javax.swing.JTextField txtaccnosave;
    private javax.swing.JTextField txtbankname;
    private javax.swing.JTextField txtroutingno;
    // End of variables declaration//GEN-END:variables
}
