/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.DriverLicenseInfo;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Urvi
 */
public class CreateDriverLicenseInfo extends javax.swing.JPanel {
    DriverLicenseInfo driverLicenseInfo;

    /**
     * Creates new form CreateDriverLicenseInfo
     */
    public CreateDriverLicenseInfo(DriverLicenseInfo driverLicenseInfo) {
        initComponents();
        this.driverLicenseInfo = driverLicenseInfo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lbllicenseinfo = new javax.swing.JLabel();
        lbllicno = new javax.swing.JLabel();
        lblissuedate = new javax.swing.JLabel();
        lblexpirydate = new javax.swing.JLabel();
        lblphoto = new javax.swing.JLabel();
        txtlicno = new javax.swing.JTextField();
        txtissuedate = new javax.swing.JTextField();
        txtexpirydate = new javax.swing.JTextField();
        txtphoto = new javax.swing.JTextField();
        btnlicsave = new javax.swing.JButton();
        btnUpload = new javax.swing.JButton();

        setBackground(new java.awt.Color(212, 196, 196));
        setLayout(new java.awt.GridBagLayout());

        lbllicenseinfo.setFont(new java.awt.Font("Footlight MT Light", 1, 26)); // NOI18N
        lbllicenseinfo.setForeground(new java.awt.Color(102, 0, 51));
        lbllicenseinfo.setText("Driver License Information");
        lbllicenseinfo.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 61, 0, 0);
        add(lbllicenseinfo, gridBagConstraints);

        lbllicno.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        lbllicno.setText("License Number:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(36, 20, 0, 0);
        add(lbllicno, gridBagConstraints);

        lblissuedate.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        lblissuedate.setText("Date Of Issue:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 36, 0, 0);
        add(lblissuedate, gridBagConstraints);

        lblexpirydate.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        lblexpirydate.setText("Date Of Expiry:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 30, 0, 0);
        add(lblexpirydate, gridBagConstraints);

        lblphoto.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        lblphoto.setText("Upload a Photo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 24, 0, 0);
        add(lblphoto, gridBagConstraints);

        txtlicno.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtlicno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlicnoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 143;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(34, 85, 0, 0);
        add(txtlicno, gridBagConstraints);

        txtissuedate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 143;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 85, 0, 0);
        add(txtissuedate, gridBagConstraints);

        txtexpirydate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 143;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 85, 0, 0);
        add(txtexpirydate, gridBagConstraints);

        txtphoto.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 143;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 85, 0, 0);
        add(txtphoto, gridBagConstraints);

        btnlicsave.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        btnlicsave.setForeground(new java.awt.Color(102, 0, 51));
        btnlicsave.setText("Save");
        btnlicsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlicsaveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(49, 48, 56, 0);
        add(btnlicsave, gridBagConstraints);

        btnUpload.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnUpload.setText("Upload");
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 5, 0, 11);
        add(btnUpload, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnlicsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlicsaveActionPerformed
        driverLicenseInfo.setLicenseNumber(txtlicno.getText());
        driverLicenseInfo.setDateOfIssue(txtissuedate.getText());
        driverLicenseInfo.setExpiryDate(txtexpirydate.getText());
        driverLicenseInfo.setPicture(txtphoto.getText());
        
        JOptionPane.showMessageDialog(this, "Information saved!");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlicsaveActionPerformed

    private void txtlicnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlicnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlicnoActionPerformed

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new java.io.File("C:/Users"));
        fileChooser.setDialogTitle("Browse Files");
        fileChooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        if(fileChooser.showOpenDialog(btnUpload) == JFileChooser.APPROVE_OPTION) {
               txtphoto.setText(fileChooser.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_btnUploadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpload;
    private javax.swing.JButton btnlicsave;
    private javax.swing.JLabel lblexpirydate;
    private javax.swing.JLabel lblissuedate;
    private javax.swing.JLabel lbllicenseinfo;
    private javax.swing.JLabel lbllicno;
    private javax.swing.JLabel lblphoto;
    private javax.swing.JTextField txtexpirydate;
    private javax.swing.JTextField txtissuedate;
    private javax.swing.JTextField txtlicno;
    private javax.swing.JTextField txtphoto;
    // End of variables declaration//GEN-END:variables
}
