/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.MedicalInfo;
import javax.swing.JOptionPane;

/**
 *
 * @author Urvi
 */
public class CreateMedicalnfo extends javax.swing.JPanel {
    MedicalInfo medicalrecordInfo;

    /**
     * Creates new form CreateMedicalnfo
     * @param medicalrecrdInfo
     */
    public CreateMedicalnfo(MedicalInfo medicalrecordInfo) {
        initComponents();
        this.medicalrecordInfo = medicalrecordInfo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblmedicalrecord = new javax.swing.JLabel();
        lblrecordno = new javax.swing.JLabel();
        lblbloodtype = new javax.swing.JLabel();
        lblallergy1 = new javax.swing.JLabel();
        lblallergy2 = new javax.swing.JLabel();
        lblallergy3 = new javax.swing.JLabel();
        txtrecordno = new javax.swing.JTextField();
        txtbloodtype = new javax.swing.JTextField();
        txtallergy1 = new javax.swing.JTextField();
        txtallergy2 = new javax.swing.JTextField();
        txtallergy3 = new javax.swing.JTextField();
        btnmedsave = new javax.swing.JButton();

        setBackground(new java.awt.Color(212, 196, 196));
        setLayout(new java.awt.GridBagLayout());

        lblmedicalrecord.setFont(new java.awt.Font("Footlight MT Light", 1, 26)); // NOI18N
        lblmedicalrecord.setForeground(new java.awt.Color(102, 0, 51));
        lblmedicalrecord.setText("Medical Record");
        lblmedicalrecord.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 106, 0, 0);
        add(lblmedicalrecord, gridBagConstraints);

        lblrecordno.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        lblrecordno.setText("Medical Record Number:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(39, 15, 0, 0);
        add(lblrecordno, gridBagConstraints);

        lblbloodtype.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        lblbloodtype.setText("Blood Type:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 102, 0, 0);
        add(lblbloodtype, gridBagConstraints);

        lblallergy1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        lblallergy1.setText("Allergy 1:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 119, 0, 0);
        add(lblallergy1, gridBagConstraints);

        lblallergy2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        lblallergy2.setText("Allergy 2:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 119, 0, 0);
        add(lblallergy2, gridBagConstraints);

        lblallergy3.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        lblallergy3.setText("Allergy 3:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 119, 0, 0);
        add(lblallergy3, gridBagConstraints);

        txtrecordno.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 143;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(37, 18, 0, 9);
        add(txtrecordno, gridBagConstraints);

        txtbloodtype.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 143;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 0, 9);
        add(txtbloodtype, gridBagConstraints);

        txtallergy1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 143;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 0, 9);
        add(txtallergy1, gridBagConstraints);

        txtallergy2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 143;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 18, 0, 9);
        add(txtallergy2, gridBagConstraints);

        txtallergy3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 143;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 0, 9);
        add(txtallergy3, gridBagConstraints);

        btnmedsave.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        btnmedsave.setForeground(new java.awt.Color(102, 0, 51));
        btnmedsave.setText("Save");
        btnmedsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmedsaveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(37, 179, 39, 0);
        add(btnmedsave, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnmedsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmedsaveActionPerformed
        medicalrecordInfo.setMedicalRecordNumber(txtrecordno.getText());
        medicalrecordInfo.setBloodType(txtbloodtype.getText());
        medicalrecordInfo.setAllergy1(txtallergy1.getText());
        medicalrecordInfo.setAllergy2(txtallergy2.getText());
        medicalrecordInfo.setAllergy3(txtallergy3.getText());
        
        JOptionPane.showMessageDialog(this, "Information saved!");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnmedsaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnmedsave;
    private javax.swing.JLabel lblallergy1;
    private javax.swing.JLabel lblallergy2;
    private javax.swing.JLabel lblallergy3;
    private javax.swing.JLabel lblbloodtype;
    private javax.swing.JLabel lblmedicalrecord;
    private javax.swing.JLabel lblrecordno;
    private javax.swing.JTextField txtallergy1;
    private javax.swing.JTextField txtallergy2;
    private javax.swing.JTextField txtallergy3;
    private javax.swing.JTextField txtbloodtype;
    private javax.swing.JTextField txtrecordno;
    // End of variables declaration//GEN-END:variables
}
