/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.AddressInfo;
import Business.BankingInfo;
import Business.CheckingAccount;
import Business.DemographicInfo;
import Business.DriverLicenseInfo;
import Business.MedicalInfo;
import Business.SavingsAccount;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Urvi
 */
public class MainJFrame extends javax.swing.JFrame {
    
    AddressInfo addInfo;
    BankingInfo bankInfo;
    DemographicInfo demoInfo;
    DriverLicenseInfo licenseInfo;
    MedicalInfo medicalInfo;
    SavingsAccount savingsAccount;
    CheckingAccount checkingAccount;

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        demoInfo = new DemographicInfo();
        addInfo = new AddressInfo();
        bankInfo = new BankingInfo();
        licenseInfo = new DriverLicenseInfo();
        medicalInfo = new MedicalInfo();
        savingsAccount = new SavingsAccount();
        checkingAccount = new CheckingAccount();
        logodisplay();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        btndemoinfo = new javax.swing.JButton();
        btnaddinfo = new javax.swing.JButton();
        btnbankinfo = new javax.swing.JButton();
        btnlicenseinfo = new javax.swing.JButton();
        btnmedicalinfo = new javax.swing.JButton();
        btnviewreport = new javax.swing.JButton();
        btnviewdemo = new javax.swing.JButton();
        btnviewadd = new javax.swing.JButton();
        btnviewbank = new javax.swing.JButton();
        btnviewlic = new javax.swing.JButton();
        btnviewmed = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblwelcome = new javax.swing.JLabel();
        lblcomname = new javax.swing.JLabel();
        lblslogan = new javax.swing.JLabel();
        lbllogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jSplitPane1.setDividerLocation(290);

        jPanel1.setBackground(new java.awt.Color(212, 196, 196));

        btndemoinfo.setBackground(new java.awt.Color(255, 204, 204));
        btndemoinfo.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        btndemoinfo.setForeground(new java.awt.Color(128, 0, 0));
        btndemoinfo.setText("Add Demographic Details");
        btndemoinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndemoinfoActionPerformed(evt);
            }
        });

        btnaddinfo.setBackground(new java.awt.Color(255, 204, 204));
        btnaddinfo.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        btnaddinfo.setForeground(new java.awt.Color(128, 0, 0));
        btnaddinfo.setText("Add Address Details");
        btnaddinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddinfoActionPerformed(evt);
            }
        });

        btnbankinfo.setBackground(new java.awt.Color(255, 204, 204));
        btnbankinfo.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        btnbankinfo.setForeground(new java.awt.Color(128, 0, 0));
        btnbankinfo.setText("Add Banking Details");
        btnbankinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbankinfoActionPerformed(evt);
            }
        });

        btnlicenseinfo.setBackground(new java.awt.Color(255, 204, 204));
        btnlicenseinfo.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        btnlicenseinfo.setForeground(new java.awt.Color(128, 0, 0));
        btnlicenseinfo.setText("Add Driver's License Details");
        btnlicenseinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlicenseinfoActionPerformed(evt);
            }
        });

        btnmedicalinfo.setBackground(new java.awt.Color(255, 204, 204));
        btnmedicalinfo.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        btnmedicalinfo.setForeground(new java.awt.Color(128, 0, 0));
        btnmedicalinfo.setText("Add Medical Record");
        btnmedicalinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmedicalinfoActionPerformed(evt);
            }
        });

        btnviewreport.setBackground(new java.awt.Color(255, 204, 204));
        btnviewreport.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        btnviewreport.setForeground(new java.awt.Color(128, 0, 0));
        btnviewreport.setText("View Report");
        btnviewreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewreportActionPerformed(evt);
            }
        });

        btnviewdemo.setBackground(new java.awt.Color(255, 204, 204));
        btnviewdemo.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        btnviewdemo.setForeground(new java.awt.Color(128, 0, 0));
        btnviewdemo.setText("View Demographic Details");
        btnviewdemo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewdemoActionPerformed(evt);
            }
        });

        btnviewadd.setBackground(new java.awt.Color(255, 204, 204));
        btnviewadd.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        btnviewadd.setForeground(new java.awt.Color(128, 0, 0));
        btnviewadd.setText("View Address Details");
        btnviewadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewaddActionPerformed(evt);
            }
        });

        btnviewbank.setBackground(new java.awt.Color(255, 204, 204));
        btnviewbank.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        btnviewbank.setForeground(new java.awt.Color(128, 0, 0));
        btnviewbank.setText("View Banking Details");
        btnviewbank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewbankActionPerformed(evt);
            }
        });

        btnviewlic.setBackground(new java.awt.Color(255, 204, 204));
        btnviewlic.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        btnviewlic.setForeground(new java.awt.Color(128, 0, 0));
        btnviewlic.setText("View Driver License Details");
        btnviewlic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewlicActionPerformed(evt);
            }
        });

        btnviewmed.setBackground(new java.awt.Color(255, 204, 204));
        btnviewmed.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        btnviewmed.setForeground(new java.awt.Color(128, 0, 0));
        btnviewmed.setText("View Medical Records");
        btnviewmed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewmedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnaddinfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnviewdemo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btndemoinfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnviewadd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnlicenseinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnviewbank, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnbankinfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnviewlic, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnmedicalinfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnviewmed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnviewreport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(234, Short.MAX_VALUE)
                .addComponent(btndemoinfo)
                .addGap(18, 18, 18)
                .addComponent(btnviewdemo)
                .addGap(18, 18, 18)
                .addComponent(btnaddinfo)
                .addGap(18, 18, 18)
                .addComponent(btnviewadd)
                .addGap(18, 18, 18)
                .addComponent(btnbankinfo)
                .addGap(18, 18, 18)
                .addComponent(btnviewbank)
                .addGap(18, 18, 18)
                .addComponent(btnlicenseinfo)
                .addGap(18, 18, 18)
                .addComponent(btnviewlic)
                .addGap(18, 18, 18)
                .addComponent(btnmedicalinfo)
                .addGap(18, 18, 18)
                .addComponent(btnviewmed)
                .addGap(18, 18, 18)
                .addComponent(btnviewreport)
                .addGap(180, 180, 180))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(212, 196, 196));

        lblwelcome.setFont(new java.awt.Font("Footlight MT Light", 0, 52)); // NOI18N
        lblwelcome.setText("WELCOME TO");

        lblcomname.setFont(new java.awt.Font("Eras Demi ITC", 1, 60)); // NOI18N
        lblcomname.setForeground(new java.awt.Color(104, 75, 75));
        lblcomname.setText("Life Health Insurance");

        lblslogan.setFont(new java.awt.Font("Edwardian Script ITC", 1, 42)); // NOI18N
        lblslogan.setForeground(new java.awt.Color(102, 0, 51));
        lblslogan.setText("Because Life is Precious!");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lbllogo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(177, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblwelcome)
                        .addGap(324, 324, 324))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblslogan)
                        .addGap(310, 310, 310))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblcomname)
                        .addGap(165, 165, 165))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbllogo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 271, Short.MAX_VALUE)
                .addComponent(lblwelcome)
                .addGap(64, 64, 64)
                .addComponent(lblcomname)
                .addGap(34, 34, 34)
                .addComponent(lblslogan)
                .addGap(313, 313, 313))
        );

        jSplitPane1.setRightComponent(jPanel2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 167;
        gridBagConstraints.ipady = 223;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jSplitPane1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndemoinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndemoinfoActionPerformed
        // TODO add your handling code here:
        CreateDemographicInfo jpdemo = new CreateDemographicInfo(demoInfo);
        jSplitPane1.setRightComponent(jpdemo);
    }//GEN-LAST:event_btndemoinfoActionPerformed

    private void btnaddinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddinfoActionPerformed
        // TODO add your handling code here:
        CreateAddressInfo jpaddress = new CreateAddressInfo(addInfo);
        jSplitPane1.setRightComponent(jpaddress);
    }//GEN-LAST:event_btnaddinfoActionPerformed

    private void btnbankinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbankinfoActionPerformed
        // TODO add your handling code here:
        CreateBankingInfo jpbank = new CreateBankingInfo(bankInfo, savingsAccount, checkingAccount);
        jSplitPane1.setRightComponent(jpbank);
    }//GEN-LAST:event_btnbankinfoActionPerformed

    private void btnlicenseinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlicenseinfoActionPerformed
        // TODO add your handling code here:
        CreateDriverLicenseInfo jplicense = new CreateDriverLicenseInfo(licenseInfo);
        jSplitPane1.setRightComponent(jplicense);
    }//GEN-LAST:event_btnlicenseinfoActionPerformed

    private void btnmedicalinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmedicalinfoActionPerformed
        // TODO add your handling code here:
        CreateMedicalnfo jpmedical = new CreateMedicalnfo(medicalInfo);
        jSplitPane1.setRightComponent(jpmedical);
    }//GEN-LAST:event_btnmedicalinfoActionPerformed

    private void btnviewreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewreportActionPerformed
        // TODO add your handling code here:
        Report report = new Report(addInfo, bankInfo, demoInfo, licenseInfo, medicalInfo, savingsAccount, checkingAccount);
        jSplitPane1.setRightComponent(report);
    }//GEN-LAST:event_btnviewreportActionPerformed

    private void btnviewaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewaddActionPerformed
        ViewAddressInfo jpaddview = new ViewAddressInfo(addInfo);
        jSplitPane1.setRightComponent(jpaddview);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnviewaddActionPerformed

    private void btnviewdemoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewdemoActionPerformed
        ViewDemographicInfo jpdemoview = new ViewDemographicInfo(demoInfo);
        jSplitPane1.setRightComponent(jpdemoview);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnviewdemoActionPerformed

    private void btnviewbankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewbankActionPerformed
        ViewBankingInfo jpbankview = new ViewBankingInfo(bankInfo, savingsAccount, checkingAccount);
        jSplitPane1.setRightComponent(jpbankview);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnviewbankActionPerformed

    private void btnviewlicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewlicActionPerformed
        ViewDriverLicenseInfo jplicview = new ViewDriverLicenseInfo(licenseInfo);
        jSplitPane1.setRightComponent(jplicview);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnviewlicActionPerformed

    private void btnviewmedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewmedActionPerformed
        ViewMedicalInfo jpmedview = new ViewMedicalInfo(medicalInfo);
        jSplitPane1.setRightComponent(jpmedview);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnviewmedActionPerformed

        /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        MainJFrame mj = new MainJFrame();
        mj.setLocationRelativeTo(null);
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddinfo;
    private javax.swing.JButton btnbankinfo;
    private javax.swing.JButton btndemoinfo;
    private javax.swing.JButton btnlicenseinfo;
    private javax.swing.JButton btnmedicalinfo;
    private javax.swing.JButton btnviewadd;
    private javax.swing.JButton btnviewbank;
    private javax.swing.JButton btnviewdemo;
    private javax.swing.JButton btnviewlic;
    private javax.swing.JButton btnviewmed;
    private javax.swing.JButton btnviewreport;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblcomname;
    private javax.swing.JLabel lbllogo;
    private javax.swing.JLabel lblslogan;
    private javax.swing.JLabel lblwelcome;
    // End of variables declaration//GEN-END:variables

    private void logodisplay() {
        ImageIcon icon = new ImageIcon("C:\\Users\\Urvi\\Desktop\\logo.png");
        Image i = icon.getImage();
        Image temp = i.getScaledInstance(100, 97, java.awt.Image.SCALE_SMOOTH);
        icon = new ImageIcon(temp);
        lbllogo.setIcon(icon);
    }
}
