/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.AddressInfo;
import Business.BankingInfo;
import Business.CheckingAccount;
import Business.DemographicInfo;
import Business.DriverLicenseInfo;
import Business.MedicalInfo;
import Business.SavingsAccount;
import java.awt.Image;
import java.awt.datatransfer.DataFlavor;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author Urvi
 */
public class Report extends javax.swing.JPanel {
    
    AddressInfo addInfo;
    BankingInfo bankInfo;
    DemographicInfo demoInfo;
    DriverLicenseInfo licenseInfo;
    MedicalInfo medicalInfo;
    SavingsAccount savingsAccount;
    CheckingAccount checkingAccount;

    /**
     * Creates new form Report
     */
    public Report(AddressInfo addInfo, BankingInfo bankInfo, DemographicInfo demoInfo, DriverLicenseInfo licenseInfo, MedicalInfo medicalInfo, SavingsAccount savingsAccount, CheckingAccount checkingAccount) {
        initComponents();
        this.demoInfo = demoInfo;
        this.addInfo = addInfo;
        this.bankInfo = bankInfo;
        this.licenseInfo = licenseInfo;
        this.medicalInfo = medicalInfo;
        this.savingsAccount = savingsAccount;
        this.checkingAccount = checkingAccount;
        displayInformation();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblpersonalinfo = new javax.swing.JLabel();
        lblbankdet = new javax.swing.JLabel();
        lbladddet = new javax.swing.JLabel();
        lbllicdet = new javax.swing.JLabel();
        lblmeddet = new javax.swing.JLabel();
        lblrvfname = new javax.swing.JLabel();
        lblrvlname = new javax.swing.JLabel();
        lblrvpno = new javax.swing.JLabel();
        lblrvdob = new javax.swing.JLabel();
        lblrvage = new javax.swing.JLabel();
        lblrvheight = new javax.swing.JLabel();
        lblrvweight = new javax.swing.JLabel();
        lblrvssn = new javax.swing.JLabel();
        lblrvstreet = new javax.swing.JLabel();
        lblrvcity = new javax.swing.JLabel();
        lblrvstate = new javax.swing.JLabel();
        lblrvzip = new javax.swing.JLabel();
        lblrvbname = new javax.swing.JLabel();
        lblrvrouting = new javax.swing.JLabel();
        lblrvsaveaccno = new javax.swing.JLabel();
        lblrvsaveaccbal = new javax.swing.JLabel();
        lblrvchkaccno = new javax.swing.JLabel();
        lblrvchkaccbal = new javax.swing.JLabel();
        lblrvlicno = new javax.swing.JLabel();
        lblrvdoi = new javax.swing.JLabel();
        lblrvdoe = new javax.swing.JLabel();
        lblrvpic = new javax.swing.JLabel();
        lblrvmedno = new javax.swing.JLabel();
        lblrvbloodtype = new javax.swing.JLabel();
        lblrvallergy1 = new javax.swing.JLabel();
        lblrvallergy2 = new javax.swing.JLabel();
        lblrvallergy3 = new javax.swing.JLabel();
        lblviewreport = new javax.swing.JLabel();
        lblfnameo = new javax.swing.JLabel();
        lbllnameo = new javax.swing.JLabel();
        lblpnoo = new javax.swing.JLabel();
        lbldobo = new javax.swing.JLabel();
        lblageo = new javax.swing.JLabel();
        lblheighto = new javax.swing.JLabel();
        lblweighto = new javax.swing.JLabel();
        lblssno = new javax.swing.JLabel();
        lblsaddo = new javax.swing.JLabel();
        lblcityo = new javax.swing.JLabel();
        lblstateo = new javax.swing.JLabel();
        lblzipo = new javax.swing.JLabel();
        lblbnameo = new javax.swing.JLabel();
        lblroutenoo = new javax.swing.JLabel();
        lblsaveaccnoo = new javax.swing.JLabel();
        lblsaveaccbalo = new javax.swing.JLabel();
        lblchkaccnoo = new javax.swing.JLabel();
        lblchkaccbalo = new javax.swing.JLabel();
        lbllno = new javax.swing.JLabel();
        lbldoio = new javax.swing.JLabel();
        lbldoeo = new javax.swing.JLabel();
        lblpico = new javax.swing.JLabel();
        lblmedreco = new javax.swing.JLabel();
        lblbloodtypeo = new javax.swing.JLabel();
        lblallergy1o = new javax.swing.JLabel();
        lblallergy2o = new javax.swing.JLabel();
        lblallergy3o = new javax.swing.JLabel();

        setBackground(new java.awt.Color(212, 196, 196));

        lblpersonalinfo.setFont(new java.awt.Font("Sitka Banner", 1, 24)); // NOI18N
        lblpersonalinfo.setForeground(new java.awt.Color(102, 0, 51));
        lblpersonalinfo.setText("Personal Information");

        lblbankdet.setFont(new java.awt.Font("Sitka Banner", 1, 24)); // NOI18N
        lblbankdet.setForeground(new java.awt.Color(102, 0, 51));
        lblbankdet.setText("Banking Details");

        lbladddet.setFont(new java.awt.Font("Sitka Banner", 1, 24)); // NOI18N
        lbladddet.setForeground(new java.awt.Color(102, 0, 51));
        lbladddet.setText("Address Details");

        lbllicdet.setFont(new java.awt.Font("Sitka Banner", 1, 24)); // NOI18N
        lbllicdet.setForeground(new java.awt.Color(102, 0, 51));
        lbllicdet.setText("License Details");

        lblmeddet.setFont(new java.awt.Font("Sitka Banner", 1, 24)); // NOI18N
        lblmeddet.setForeground(new java.awt.Color(102, 0, 51));
        lblmeddet.setText("Medical Record");

        lblrvfname.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        lblrvfname.setText("First Name:");

        lblrvlname.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        lblrvlname.setText("Last Name:");

        lblrvpno.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        lblrvpno.setText("Phone Number:");

        lblrvdob.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        lblrvdob.setText("Date Of Birth:");

        lblrvage.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        lblrvage.setText("Age:");

        lblrvheight.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        lblrvheight.setText("Height:");

        lblrvweight.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        lblrvweight.setText("Weight:");

        lblrvssn.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        lblrvssn.setText("SSN:");

        lblrvstreet.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        lblrvstreet.setText("Street Address:");

        lblrvcity.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        lblrvcity.setText("City:");

        lblrvstate.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        lblrvstate.setText("State:");

        lblrvzip.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        lblrvzip.setText("Zip Code:");

        lblrvbname.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        lblrvbname.setText("Bank Name:");

        lblrvrouting.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        lblrvrouting.setText("Bank Routing Number:");

        lblrvsaveaccno.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        lblrvsaveaccno.setText("Savings Account Number:");

        lblrvsaveaccbal.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        lblrvsaveaccbal.setText("Savings Account Balance:");

        lblrvchkaccno.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        lblrvchkaccno.setText("Checking Account Number:");

        lblrvchkaccbal.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        lblrvchkaccbal.setText("Checking Account Balance:");

        lblrvlicno.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        lblrvlicno.setText("License Number:");

        lblrvdoi.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        lblrvdoi.setText("Date Of Issue:");

        lblrvdoe.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        lblrvdoe.setText("Date Of Expiry:");

        lblrvpic.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        lblrvpic.setText("Picture:");

        lblrvmedno.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        lblrvmedno.setText("Medical Record Number:");

        lblrvbloodtype.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        lblrvbloodtype.setText("Blood Type:");

        lblrvallergy1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        lblrvallergy1.setText("Allergy 1:");

        lblrvallergy2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        lblrvallergy2.setText("Allergy 2:");

        lblrvallergy3.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        lblrvallergy3.setText("Allergy 3:");

        lblviewreport.setFont(new java.awt.Font("Garamond", 1, 48)); // NOI18N
        lblviewreport.setForeground(new java.awt.Color(102, 0, 51));
        lblviewreport.setText("Report");

        lblfnameo.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        lbllnameo.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        lblpnoo.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        lbldobo.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        lblageo.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        lblheighto.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        lblweighto.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        lblssno.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        lblsaddo.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        lblcityo.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        lblstateo.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        lblzipo.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        lblbnameo.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        lblroutenoo.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        lblsaveaccnoo.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        lblsaveaccbalo.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        lblchkaccnoo.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        lblchkaccbalo.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        lbllno.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        lbldoio.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        lbldoeo.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        lblpico.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        lblmedreco.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        lblbloodtypeo.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        lblallergy1o.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        lblallergy2o.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        lblallergy3o.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblrvrouting)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblrvbname)
                                    .addComponent(lblbankdet))
                                .addGap(197, 197, 197)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblmeddet)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblrvmedno)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblbloodtypeo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblmedreco, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(84, 84, 84))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lblrvzip)
                                    .addGap(300, 300, 300)
                                    .addComponent(lblrvpic, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblrvdob)
                                    .addGap(92, 92, 92)
                                    .addComponent(lbldobo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(46, 46, 46)
                                    .addComponent(lblrvssn)
                                    .addGap(122, 122, 122)
                                    .addComponent(lblssno, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(102, 102, 102)))
                            .addComponent(lblrvchkaccbal))
                        .addGap(0, 18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblrvchkaccno)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(170, 170, 170)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblcityo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblsaddo, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblpnoo, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblbnameo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblstateo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblzipo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbllnameo, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblfnameo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addComponent(lblrvage))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblrvsaveaccno)
                                    .addComponent(lblrvsaveaccbal))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(204, 204, 204)
                                        .addComponent(lblrvbloodtype))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblchkaccnoo, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblroutenoo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblsaveaccnoo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblsaveaccbalo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblchkaccbalo, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblrvallergy2)
                                            .addComponent(lblrvallergy1)
                                            .addComponent(lblrvallergy3))))))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblageo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblweighto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblheighto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblallergy1o, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                                    .addComponent(lblallergy3o, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblallergy2o, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(lblviewreport))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(lblpersonalinfo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(lblrvpno)
                        .addGap(264, 264, 264)
                        .addComponent(lblrvweight))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(lblrvcity)
                        .addGap(327, 327, 327)
                        .addComponent(lblrvdoi, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(lbldoio, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblrvstreet)
                            .addComponent(lbladddet))
                        .addGap(202, 202, 202)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbllicdet)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblrvlicno)
                                .addGap(46, 46, 46)
                                .addComponent(lbllno, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(lblrvstate)
                        .addGap(320, 320, 320)
                        .addComponent(lblrvdoe)
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblpico, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbldoeo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblrvfname)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblrvlname)
                                .addGap(289, 289, 289)
                                .addComponent(lblrvheight)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblviewreport)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblpersonalinfo)
                        .addGap(17, 17, 17)
                        .addComponent(lblageo, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblheighto, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(lblweighto, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblfnameo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblrvfname)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblrvage)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblrvlname)
                                    .addComponent(lblrvheight)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbllnameo, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblrvpno)
                            .addComponent(lblrvweight)
                            .addComponent(lblpnoo, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblrvdob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblrvssn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblssno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbldobo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbladddet)
                            .addComponent(lbllicdet))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(lblrvstreet))
                            .addComponent(lblrvlicno)
                            .addComponent(lbllno, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblsaddo, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblrvdoi)
                    .addComponent(lbldoio, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lblrvcity))
                    .addComponent(lblcityo, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblrvdoe)
                    .addComponent(lbldoeo, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lblrvstate))
                    .addComponent(lblstateo, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblrvzip, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblzipo, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblrvpic, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(118, 118, 118)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblbankdet, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblmeddet, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(lblpico, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblrvbname))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblrvmedno)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addComponent(lblmedreco, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblbnameo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(lblrvrouting))
                                    .addComponent(lblbloodtypeo, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblroutenoo, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(lblrvsaveaccno))
                            .addComponent(lblsaveaccnoo, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblsaveaccbalo, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblrvsaveaccbal)
                            .addComponent(lblrvallergy2))
                        .addGap(2, 2, 2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblrvbloodtype)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblallergy1o, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblallergy2o, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblrvallergy1))))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblchkaccnoo, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblrvallergy3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblallergy3o, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblrvchkaccno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblrvchkaccbal, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                    .addComponent(lblchkaccbalo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbladddet;
    private javax.swing.JLabel lblageo;
    private javax.swing.JLabel lblallergy1o;
    private javax.swing.JLabel lblallergy2o;
    private javax.swing.JLabel lblallergy3o;
    private javax.swing.JLabel lblbankdet;
    private javax.swing.JLabel lblbloodtypeo;
    private javax.swing.JLabel lblbnameo;
    private javax.swing.JLabel lblchkaccbalo;
    private javax.swing.JLabel lblchkaccnoo;
    private javax.swing.JLabel lblcityo;
    private javax.swing.JLabel lbldobo;
    private javax.swing.JLabel lbldoeo;
    private javax.swing.JLabel lbldoio;
    private javax.swing.JLabel lblfnameo;
    private javax.swing.JLabel lblheighto;
    private javax.swing.JLabel lbllicdet;
    private javax.swing.JLabel lbllnameo;
    private javax.swing.JLabel lbllno;
    private javax.swing.JLabel lblmeddet;
    private javax.swing.JLabel lblmedreco;
    private javax.swing.JLabel lblpersonalinfo;
    private javax.swing.JLabel lblpico;
    private javax.swing.JLabel lblpnoo;
    private javax.swing.JLabel lblroutenoo;
    private javax.swing.JLabel lblrvage;
    private javax.swing.JLabel lblrvallergy1;
    private javax.swing.JLabel lblrvallergy2;
    private javax.swing.JLabel lblrvallergy3;
    private javax.swing.JLabel lblrvbloodtype;
    private javax.swing.JLabel lblrvbname;
    private javax.swing.JLabel lblrvchkaccbal;
    private javax.swing.JLabel lblrvchkaccno;
    private javax.swing.JLabel lblrvcity;
    private javax.swing.JLabel lblrvdob;
    private javax.swing.JLabel lblrvdoe;
    private javax.swing.JLabel lblrvdoi;
    private javax.swing.JLabel lblrvfname;
    private javax.swing.JLabel lblrvheight;
    private javax.swing.JLabel lblrvlicno;
    private javax.swing.JLabel lblrvlname;
    private javax.swing.JLabel lblrvmedno;
    private javax.swing.JLabel lblrvpic;
    private javax.swing.JLabel lblrvpno;
    private javax.swing.JLabel lblrvrouting;
    private javax.swing.JLabel lblrvsaveaccbal;
    private javax.swing.JLabel lblrvsaveaccno;
    private javax.swing.JLabel lblrvssn;
    private javax.swing.JLabel lblrvstate;
    private javax.swing.JLabel lblrvstreet;
    private javax.swing.JLabel lblrvweight;
    private javax.swing.JLabel lblrvzip;
    private javax.swing.JLabel lblsaddo;
    private javax.swing.JLabel lblsaveaccbalo;
    private javax.swing.JLabel lblsaveaccnoo;
    private javax.swing.JLabel lblssno;
    private javax.swing.JLabel lblstateo;
    private javax.swing.JLabel lblviewreport;
    private javax.swing.JLabel lblweighto;
    private javax.swing.JLabel lblzipo;
    // End of variables declaration//GEN-END:variables

    private void displayInformation() {
        ImageIcon icon = new ImageIcon(licenseInfo.getPicture());
        Image i = icon.getImage();
        Image temp = i.getScaledInstance(120, 120, java.awt.Image.SCALE_SMOOTH);
        icon = new ImageIcon(temp);
        lblfnameo.setText(demoInfo.getFirstName());
        lbllnameo.setText(demoInfo.getLastName());
        lblpnoo.setText(demoInfo.getPhoneNo());
        lbldobo.setText(demoInfo.getDateOfBirth());
        lblageo.setText(demoInfo.getAge());
        lblheighto.setText(demoInfo.getHeight());
        lblweighto.setText(demoInfo.getWeight());
        lblssno.setText(demoInfo.getSSN());
        lblsaddo.setText(addInfo.getStreetAddress());
        lblcityo.setText(addInfo.getCity());
        lblstateo.setText(addInfo.getState());
        lblzipo.setText(addInfo.getZipCode());
        lblbnameo.setText(bankInfo.getBankName());
        lblroutenoo.setText(bankInfo.getBankRoutingNumber());
        lblsaveaccnoo.setText(savingsAccount.getSavebankAccNumber());
        lblsaveaccbalo.setText(savingsAccount.getSaveaccBalance());
        lblchkaccnoo.setText(checkingAccount.getChkbankAccNumber());
        lblchkaccbalo.setText(checkingAccount.getChkaccBalance());
        lbllno.setText(licenseInfo.getLicenseNumber());
        lbldoio.setText(licenseInfo.getDateOfIssue());
        lbldoeo.setText(licenseInfo.getExpiryDate());
        lblpico.setIcon(icon);
        lblmedreco.setText(medicalInfo.getMedicalRecordNumber());
        lblbloodtypeo.setText(medicalInfo.getBloodType());
        lblallergy1o.setText(medicalInfo.getAllergy1());
        lblallergy2o.setText(medicalInfo.getAllergy2());
        lblallergy3o.setText(medicalInfo.getAllergy3());
    }

    
}
