/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.DemographicInfo;
import Business.DriverLicenseInfo;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Urvi
 */
public class ViewDriverLicenseInfo extends javax.swing.JPanel {
    DriverLicenseInfo licenseInfo;
    /**
     * Creates new form ViewDriverLicenseInfo
     */
    public ViewDriverLicenseInfo(DriverLicenseInfo licenseInfo) {
        initComponents();
        this.licenseInfo = licenseInfo;
        displaylicview();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lbllicenseinfoview = new javax.swing.JLabel();
        lbllicnoview = new javax.swing.JLabel();
        lblissuedateview = new javax.swing.JLabel();
        lblexpirydateview = new javax.swing.JLabel();
        lblphotoview = new javax.swing.JLabel();
        txtlicnoview = new javax.swing.JTextField();
        txtissuedateview = new javax.swing.JTextField();
        txtexpirydateview = new javax.swing.JTextField();
        lblpicview = new javax.swing.JLabel();

        setBackground(new java.awt.Color(212, 196, 196));
        setLayout(new java.awt.GridBagLayout());

        lbllicenseinfoview.setFont(new java.awt.Font("Footlight MT Light", 1, 26)); // NOI18N
        lbllicenseinfoview.setForeground(new java.awt.Color(102, 0, 0));
        lbllicenseinfoview.setText("Driver License Information");
        lbllicenseinfoview.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 44, 0, 0);
        add(lbllicenseinfoview, gridBagConstraints);

        lbllicnoview.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        lbllicnoview.setText("License Number:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 18, 0, 0);
        add(lbllicnoview, gridBagConstraints);

        lblissuedateview.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        lblissuedateview.setText("Date Of Issue:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 34, 0, 0);
        add(lblissuedateview, gridBagConstraints);

        lblexpirydateview.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        lblexpirydateview.setText("Date Of Expiry:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 28, 0, 0);
        add(lblexpirydateview, gridBagConstraints);

        lblphotoview.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        lblphotoview.setText("Upload a Photo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 22, 0, 0);
        add(lblphotoview, gridBagConstraints);

        txtlicnoview.setEditable(false);
        txtlicnoview.setBackground(new java.awt.Color(212, 196, 196));
        txtlicnoview.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtlicnoview.setBorder(null);
        txtlicnoview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlicnoviewActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 143;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(36, 84, 0, 40);
        add(txtlicnoview, gridBagConstraints);

        txtissuedateview.setEditable(false);
        txtissuedateview.setBackground(new java.awt.Color(212, 196, 196));
        txtissuedateview.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtissuedateview.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 143;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 82, 0, 0);
        add(txtissuedateview, gridBagConstraints);

        txtexpirydateview.setEditable(false);
        txtexpirydateview.setBackground(new java.awt.Color(212, 196, 196));
        txtexpirydateview.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtexpirydateview.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 143;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 84, 0, 40);
        add(txtexpirydateview, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.ipady = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 79, 11, 0);
        add(lblpicview, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void txtlicnoviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlicnoviewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlicnoviewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblexpirydateview;
    private javax.swing.JLabel lblissuedateview;
    private javax.swing.JLabel lbllicenseinfoview;
    private javax.swing.JLabel lbllicnoview;
    private javax.swing.JLabel lblphotoview;
    private javax.swing.JLabel lblpicview;
    private javax.swing.JTextField txtexpirydateview;
    private javax.swing.JTextField txtissuedateview;
    private javax.swing.JTextField txtlicnoview;
    // End of variables declaration//GEN-END:variables

    private void displaylicview() {
        ImageIcon icon = new ImageIcon(licenseInfo.getPicture());
        Image i = icon.getImage();
        Image temp = i.getScaledInstance(100, 100, java.awt.Image.SCALE_SMOOTH);
        icon = new ImageIcon(temp);
        txtlicnoview.setText(licenseInfo.getLicenseNumber());
        txtissuedateview.setText(licenseInfo.getDateOfIssue());
        txtexpirydateview.setText(licenseInfo.getExpiryDate());
        lblpicview.setIcon(icon);
    }
}
