/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.MedicalInfo;

/**
 *
 * @author Urvi
 */
public class ViewMedicalInfo extends javax.swing.JPanel {
    MedicalInfo medicalInfo;
    /**
     * Creates new form ViewMedicalInfo
     */
    public ViewMedicalInfo(MedicalInfo medicalInfo) {
        initComponents();
        this.medicalInfo = medicalInfo;
        displaymedicalview();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblmedicalrecordview = new javax.swing.JLabel();
        lblrecordnoview = new javax.swing.JLabel();
        lblbloodtypeview = new javax.swing.JLabel();
        lblallergy1view = new javax.swing.JLabel();
        lblallergy2view = new javax.swing.JLabel();
        lblallergy3view = new javax.swing.JLabel();
        txtrecordnoview = new javax.swing.JTextField();
        txtbloodtypeview = new javax.swing.JTextField();
        txtallergy1view = new javax.swing.JTextField();
        txtallergy2view = new javax.swing.JTextField();
        txtallergy3view = new javax.swing.JTextField();

        setBackground(new java.awt.Color(212, 196, 196));
        setLayout(new java.awt.GridBagLayout());

        lblmedicalrecordview.setFont(new java.awt.Font("Footlight MT Light", 1, 26)); // NOI18N
        lblmedicalrecordview.setForeground(new java.awt.Color(102, 0, 0));
        lblmedicalrecordview.setText("Medical Record");
        lblmedicalrecordview.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(39, 103, 0, 0);
        add(lblmedicalrecordview, gridBagConstraints);

        lblrecordnoview.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        lblrecordnoview.setText("Medical Record Number:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(39, 12, 0, 0);
        add(lblrecordnoview, gridBagConstraints);

        lblbloodtypeview.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        lblbloodtypeview.setText("Blood Type:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 96, 0, 0);
        add(lblbloodtypeview, gridBagConstraints);

        lblallergy1view.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        lblallergy1view.setText("Allergy 1:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 113, 0, 0);
        add(lblallergy1view, gridBagConstraints);

        lblallergy2view.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        lblallergy2view.setText("Allergy 2:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 113, 0, 0);
        add(lblallergy2view, gridBagConstraints);

        lblallergy3view.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        lblallergy3view.setText("Allergy 3:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 113, 19, 0);
        add(lblallergy3view, gridBagConstraints);

        txtrecordnoview.setEditable(false);
        txtrecordnoview.setBackground(new java.awt.Color(212, 196, 196));
        txtrecordnoview.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtrecordnoview.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 143;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(39, 74, 0, 20);
        add(txtrecordnoview, gridBagConstraints);

        txtbloodtypeview.setEditable(false);
        txtbloodtypeview.setBackground(new java.awt.Color(212, 196, 196));
        txtbloodtypeview.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtbloodtypeview.setBorder(null);
        txtbloodtypeview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbloodtypeviewActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 143;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 74, 0, 20);
        add(txtbloodtypeview, gridBagConstraints);

        txtallergy1view.setEditable(false);
        txtallergy1view.setBackground(new java.awt.Color(212, 196, 196));
        txtallergy1view.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtallergy1view.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 143;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 74, 0, 20);
        add(txtallergy1view, gridBagConstraints);

        txtallergy2view.setEditable(false);
        txtallergy2view.setBackground(new java.awt.Color(212, 196, 196));
        txtallergy2view.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtallergy2view.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 143;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 74, 0, 20);
        add(txtallergy2view, gridBagConstraints);

        txtallergy3view.setEditable(false);
        txtallergy3view.setBackground(new java.awt.Color(212, 196, 196));
        txtallergy3view.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtallergy3view.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 143;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 74, 0, 20);
        add(txtallergy3view, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void txtbloodtypeviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbloodtypeviewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbloodtypeviewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblallergy1view;
    private javax.swing.JLabel lblallergy2view;
    private javax.swing.JLabel lblallergy3view;
    private javax.swing.JLabel lblbloodtypeview;
    private javax.swing.JLabel lblmedicalrecordview;
    private javax.swing.JLabel lblrecordnoview;
    private javax.swing.JTextField txtallergy1view;
    private javax.swing.JTextField txtallergy2view;
    private javax.swing.JTextField txtallergy3view;
    private javax.swing.JTextField txtbloodtypeview;
    private javax.swing.JTextField txtrecordnoview;
    // End of variables declaration//GEN-END:variables

    private void displaymedicalview() {
        txtrecordnoview.setText(medicalInfo.getMedicalRecordNumber());
        txtbloodtypeview.setText(medicalInfo.getBloodType());
        txtallergy1view.setText(medicalInfo.getAllergy1());
        txtallergy2view.setText(medicalInfo.getAllergy2());
        txtallergy3view.setText(medicalInfo.getAllergy3());
    }
}
