/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.DemographicInfo;

/**
 *
 * @author Urvi
 */
public class ViewDemographicInfo extends javax.swing.JPanel {
    DemographicInfo demoInfo;
    /**
     * Creates new form ViewDemographicInfo
     */
    public ViewDemographicInfo(DemographicInfo demoInfo) {
        initComponents();
        this.demoInfo = demoInfo;
        displaydemoview();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblDemoInfoview = new javax.swing.JLabel();
        lblfnameview = new javax.swing.JLabel();
        lbllnameview = new javax.swing.JLabel();
        lblphonenumberview = new javax.swing.JLabel();
        lbldobview = new javax.swing.JLabel();
        lblageview = new javax.swing.JLabel();
        lblheightview = new javax.swing.JLabel();
        lblweightview = new javax.swing.JLabel();
        lblssnview = new javax.swing.JLabel();
        txtfnameview = new javax.swing.JTextField();
        txtlnameview = new javax.swing.JTextField();
        txtphonenumberview = new javax.swing.JTextField();
        txtdobview = new javax.swing.JTextField();
        txtageview = new javax.swing.JTextField();
        txtheightview = new javax.swing.JTextField();
        txtweightview = new javax.swing.JTextField();
        txtssnview = new javax.swing.JTextField();

        setBackground(new java.awt.Color(212, 196, 196));
        setLayout(new java.awt.GridBagLayout());

        lblDemoInfoview.setFont(new java.awt.Font("Footlight MT Light", 1, 26)); // NOI18N
        lblDemoInfoview.setForeground(new java.awt.Color(102, 0, 0));
        lblDemoInfoview.setText("Demographic Information");
        lblDemoInfoview.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(41, 89, 0, 0);
        add(lblDemoInfoview, gridBagConstraints);

        lblfnameview.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        lblfnameview.setText("First Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 145, 0, 0);
        add(lblfnameview, gridBagConstraints);

        lbllnameview.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        lbllnameview.setText("Last Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 147, 0, 0);
        add(lbllnameview, gridBagConstraints);

        lblphonenumberview.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        lblphonenumberview.setText("Phone Number:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 116, 0, 0);
        add(lblphonenumberview, gridBagConstraints);

        lbldobview.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        lbldobview.setText("Date Of Birth(mm/dd/yyyy):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 28, 0, 0);
        add(lbldobview, gridBagConstraints);

        lblageview.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        lblageview.setText("Age:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 191, 0, 0);
        add(lblageview, gridBagConstraints);

        lblheightview.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        lblheightview.setText("Height(cms):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 134, 0, 0);
        add(lblheightview, gridBagConstraints);

        lblweightview.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        lblweightview.setText("Weight(pounds):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 107, 0, 0);
        add(lblweightview, gridBagConstraints);

        lblssnview.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        lblssnview.setText("Social Security Number:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 60, 39, 0);
        add(lblssnview, gridBagConstraints);

        txtfnameview.setEditable(false);
        txtfnameview.setBackground(new java.awt.Color(212, 196, 196));
        txtfnameview.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtfnameview.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 143;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 91, 0, 28);
        add(txtfnameview, gridBagConstraints);

        txtlnameview.setEditable(false);
        txtlnameview.setBackground(new java.awt.Color(212, 196, 196));
        txtlnameview.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtlnameview.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 143;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 91, 0, 28);
        add(txtlnameview, gridBagConstraints);

        txtphonenumberview.setEditable(false);
        txtphonenumberview.setBackground(new java.awt.Color(212, 196, 196));
        txtphonenumberview.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtphonenumberview.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 143;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 91, 0, 28);
        add(txtphonenumberview, gridBagConstraints);

        txtdobview.setEditable(false);
        txtdobview.setBackground(new java.awt.Color(212, 196, 196));
        txtdobview.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtdobview.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 143;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 91, 0, 28);
        add(txtdobview, gridBagConstraints);

        txtageview.setEditable(false);
        txtageview.setBackground(new java.awt.Color(212, 196, 196));
        txtageview.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtageview.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 143;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 91, 0, 28);
        add(txtageview, gridBagConstraints);

        txtheightview.setEditable(false);
        txtheightview.setBackground(new java.awt.Color(212, 196, 196));
        txtheightview.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtheightview.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 143;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 91, 0, 28);
        add(txtheightview, gridBagConstraints);

        txtweightview.setEditable(false);
        txtweightview.setBackground(new java.awt.Color(212, 196, 196));
        txtweightview.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtweightview.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 143;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 91, 0, 28);
        add(txtweightview, gridBagConstraints);

        txtssnview.setEditable(false);
        txtssnview.setBackground(new java.awt.Color(212, 196, 196));
        txtssnview.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtssnview.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 143;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 91, 0, 28);
        add(txtssnview, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDemoInfoview;
    private javax.swing.JLabel lblageview;
    private javax.swing.JLabel lbldobview;
    private javax.swing.JLabel lblfnameview;
    private javax.swing.JLabel lblheightview;
    private javax.swing.JLabel lbllnameview;
    private javax.swing.JLabel lblphonenumberview;
    private javax.swing.JLabel lblssnview;
    private javax.swing.JLabel lblweightview;
    private javax.swing.JTextField txtageview;
    private javax.swing.JTextField txtdobview;
    private javax.swing.JTextField txtfnameview;
    private javax.swing.JTextField txtheightview;
    private javax.swing.JTextField txtlnameview;
    private javax.swing.JTextField txtphonenumberview;
    private javax.swing.JTextField txtssnview;
    private javax.swing.JTextField txtweightview;
    // End of variables declaration//GEN-END:variables

    private void displaydemoview() {
        txtfnameview.setText(demoInfo.getFirstName());
        txtlnameview.setText(demoInfo.getLastName());
        txtphonenumberview.setText(demoInfo.getPhoneNo());
        txtdobview.setText(demoInfo.getDateOfBirth());
        txtageview.setText(demoInfo.getAge());
        txtheightview.setText(demoInfo.getHeight());
        txtweightview.setText(demoInfo.getWeight());
        txtssnview.setText(demoInfo.getSSN());
    }
}
