/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.AddressInfo;

/**
 *
 * @author Urvi
 */
public class ViewAddressInfo extends javax.swing.JPanel {
    AddressInfo addInfo;
    /**
     * Creates new form ViewAddressInfo
     */
    public ViewAddressInfo(AddressInfo addInfo) {
        initComponents();
        this.addInfo = addInfo;
        displayaddview();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lbladdressinfoview = new javax.swing.JLabel();
        lblstreetaddview = new javax.swing.JLabel();
        lblcityview = new javax.swing.JLabel();
        lblstateview = new javax.swing.JLabel();
        lblzipcodeview = new javax.swing.JLabel();
        txtstreetaddview = new javax.swing.JTextField();
        txtcityview = new javax.swing.JTextField();
        txtstateview = new javax.swing.JTextField();
        txtzipcodeview = new javax.swing.JTextField();

        setBackground(new java.awt.Color(212, 196, 196));
        setLayout(new java.awt.GridBagLayout());

        lbladdressinfoview.setFont(new java.awt.Font("Footlight MT Light", 1, 26)); // NOI18N
        lbladdressinfoview.setForeground(new java.awt.Color(102, 0, 0));
        lbladdressinfoview.setText("Address Information");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 83, 0, 0);
        add(lbladdressinfoview, gridBagConstraints);

        lblstreetaddview.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        lblstreetaddview.setText("Street Address:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(39, 47, 0, 0);
        add(lblstreetaddview, gridBagConstraints);

        lblcityview.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        lblcityview.setText("City:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(34, 120, 0, 0);
        add(lblcityview, gridBagConstraints);

        lblstateview.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        lblstateview.setText("State:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(31, 111, 0, 0);
        add(lblstateview, gridBagConstraints);

        lblzipcodeview.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        lblzipcodeview.setText("ZipCode:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 90, 32, 0);
        add(lblzipcodeview, gridBagConstraints);

        txtstreetaddview.setEditable(false);
        txtstreetaddview.setBackground(new java.awt.Color(212, 196, 196));
        txtstreetaddview.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtstreetaddview.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 144;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(39, 51, 0, 0);
        add(txtstreetaddview, gridBagConstraints);

        txtcityview.setEditable(false);
        txtcityview.setBackground(new java.awt.Color(212, 196, 196));
        txtcityview.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtcityview.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 144;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(34, 51, 0, 0);
        add(txtcityview, gridBagConstraints);

        txtstateview.setEditable(false);
        txtstateview.setBackground(new java.awt.Color(212, 196, 196));
        txtstateview.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtstateview.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 144;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(31, 53, 0, 52);
        add(txtstateview, gridBagConstraints);

        txtzipcodeview.setEditable(false);
        txtzipcodeview.setBackground(new java.awt.Color(212, 196, 196));
        txtzipcodeview.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtzipcodeview.setBorder(null);
        txtzipcodeview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtzipcodeviewActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 144;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 53, 0, 52);
        add(txtzipcodeview, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void txtzipcodeviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtzipcodeviewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtzipcodeviewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbladdressinfoview;
    private javax.swing.JLabel lblcityview;
    private javax.swing.JLabel lblstateview;
    private javax.swing.JLabel lblstreetaddview;
    private javax.swing.JLabel lblzipcodeview;
    private javax.swing.JTextField txtcityview;
    private javax.swing.JTextField txtstateview;
    private javax.swing.JTextField txtstreetaddview;
    private javax.swing.JTextField txtzipcodeview;
    // End of variables declaration//GEN-END:variables

    private void displayaddview() {
        txtstreetaddview.setText(addInfo.getStreetAddress());
        txtcityview.setText(addInfo.getCity());
        txtstateview.setText(addInfo.getState());
        txtzipcodeview.setText(addInfo.getZipCode());
    }
}
