/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.BankingInfo;
import Business.CheckingAccount;
import Business.SavingsAccount;

/**
 *
 * @author Urvi
 */
public class ViewBankingInfo extends javax.swing.JPanel {
    BankingInfo bankInfo;
    SavingsAccount savingsAccount;
    CheckingAccount checkingAccount;
    /**
     * Creates new form ViewBankingInfo
     */
    public ViewBankingInfo(BankingInfo bankInfo,SavingsAccount savingsAccount,CheckingAccount checkingAccount) {
        initComponents();
        this.bankInfo = bankInfo;
        this.savingsAccount = savingsAccount;
        this.checkingAccount = checkingAccount;
        displaybankview();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblbankinginfoview = new javax.swing.JLabel();
        lblbanknameview = new javax.swing.JLabel();
        lblbankroutingnoview = new javax.swing.JLabel();
        lblacctypesaveview = new javax.swing.JLabel();
        lblacctypechkview = new javax.swing.JLabel();
        lblsaveaccnoview = new javax.swing.JLabel();
        lblsaveaccbalview = new javax.swing.JLabel();
        lblchkaccnoview = new javax.swing.JLabel();
        lblchkaccbalview = new javax.swing.JLabel();
        txtbanknameview = new javax.swing.JTextField();
        txtroutingnoview = new javax.swing.JTextField();
        txtsaveaccnoview = new javax.swing.JTextField();
        txtsaveaccbalview = new javax.swing.JTextField();
        txtchkaccnoview = new javax.swing.JTextField();
        txtchkaccbalview = new javax.swing.JTextField();

        setBackground(new java.awt.Color(212, 196, 196));
        setLayout(new java.awt.GridBagLayout());

        lblbankinginfoview.setFont(new java.awt.Font("Footlight MT Light", 1, 26)); // NOI18N
        lblbankinginfoview.setForeground(new java.awt.Color(102, 0, 0));
        lblbankinginfoview.setText("Banking Information");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(51, 33, 0, 0);
        add(lblbankinginfoview, gridBagConstraints);

        lblbanknameview.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        lblbanknameview.setText("Bank Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(45, 49, 0, 0);
        add(lblbanknameview, gridBagConstraints);

        lblbankroutingnoview.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        lblbankroutingnoview.setText("Bank Routing Number:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(22, 145, 0, 0);
        add(lblbankroutingnoview, gridBagConstraints);

        lblacctypesaveview.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        lblacctypesaveview.setText("Savings Account");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(108, 50, 0, 0);
        add(lblacctypesaveview, gridBagConstraints);

        lblacctypechkview.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        lblacctypechkview.setText("Checking Account");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(108, 33, 0, 0);
        add(lblacctypechkview, gridBagConstraints);

        lblsaveaccnoview.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        lblsaveaccnoview.setText("Account Number:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 50, 0, 0);
        add(lblsaveaccnoview, gridBagConstraints);

        lblsaveaccbalview.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        lblsaveaccbalview.setText("Account Balance:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 50, 26, 0);
        add(lblsaveaccbalview, gridBagConstraints);

        lblchkaccnoview.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        lblchkaccnoview.setText("Account Number:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 34, 0, 0);
        add(lblchkaccnoview, gridBagConstraints);

        lblchkaccbalview.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        lblchkaccbalview.setText("Account Balance:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 34, 0, 0);
        add(lblchkaccbalview, gridBagConstraints);

        txtbanknameview.setEditable(false);
        txtbanknameview.setBackground(new java.awt.Color(212, 196, 196));
        txtbanknameview.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtbanknameview.setBorder(null);
        txtbanknameview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbanknameviewActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.ipadx = 133;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(45, 42, 0, 0);
        add(txtbanknameview, gridBagConstraints);

        txtroutingnoview.setEditable(false);
        txtroutingnoview.setBackground(new java.awt.Color(212, 196, 196));
        txtroutingnoview.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtroutingnoview.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 12;
        gridBagConstraints.ipadx = 133;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 55, 0, 0);
        add(txtroutingnoview, gridBagConstraints);

        txtsaveaccnoview.setEditable(false);
        txtsaveaccnoview.setBackground(new java.awt.Color(212, 196, 196));
        txtsaveaccnoview.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtsaveaccnoview.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 133;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 27, 0, 0);
        add(txtsaveaccnoview, gridBagConstraints);

        txtsaveaccbalview.setEditable(false);
        txtsaveaccbalview.setBackground(new java.awt.Color(212, 196, 196));
        txtsaveaccbalview.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtsaveaccbalview.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 134;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 27, 0, 0);
        add(txtsaveaccbalview, gridBagConstraints);

        txtchkaccnoview.setEditable(false);
        txtchkaccnoview.setBackground(new java.awt.Color(212, 196, 196));
        txtchkaccnoview.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtchkaccnoview.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 20;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.ipadx = 123;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 11, 0, 10);
        add(txtchkaccnoview, gridBagConstraints);

        txtchkaccbalview.setEditable(false);
        txtchkaccbalview.setBackground(new java.awt.Color(212, 196, 196));
        txtchkaccbalview.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtchkaccbalview.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 20;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.ipadx = 124;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 10, 0, 10);
        add(txtchkaccbalview, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void txtbanknameviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbanknameviewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbanknameviewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblacctypechkview;
    private javax.swing.JLabel lblacctypesaveview;
    private javax.swing.JLabel lblbankinginfoview;
    private javax.swing.JLabel lblbanknameview;
    private javax.swing.JLabel lblbankroutingnoview;
    private javax.swing.JLabel lblchkaccbalview;
    private javax.swing.JLabel lblchkaccnoview;
    private javax.swing.JLabel lblsaveaccbalview;
    private javax.swing.JLabel lblsaveaccnoview;
    private javax.swing.JTextField txtbanknameview;
    private javax.swing.JTextField txtchkaccbalview;
    private javax.swing.JTextField txtchkaccnoview;
    private javax.swing.JTextField txtroutingnoview;
    private javax.swing.JTextField txtsaveaccbalview;
    private javax.swing.JTextField txtsaveaccnoview;
    // End of variables declaration//GEN-END:variables

    private void displaybankview() {
        txtbanknameview.setText(bankInfo.getBankName());
        txtroutingnoview.setText(bankInfo.getBankRoutingNumber());
        txtsaveaccnoview.setText(savingsAccount.getSavebankAccNumber());
        txtsaveaccbalview.setText(savingsAccount.getSaveaccBalance());
        txtchkaccnoview.setText(checkingAccount.getChkbankAccNumber());
        txtchkaccbalview.setText(checkingAccount.getChkaccBalance());    
    }
}
